package bottools

import (
	"fmt"
	"os"
	"reflect"
	"slices"
	"strings"

	ei "github.com/mkmccarty/TokenTimeBoostBot/src/ei"
)

// ---- Filters ----

// Fields we never include in any snapshot
var (
	globalExcludes = []string{
		"state", "sizeCache", "unknownFields",
	}

	// Whitelist per struct (fields to keep)
	snapshotFieldWhitelist = map[string][]string{
		"ContractCoopStatusResponse_ContributionInfo": {
			"Uuid",
			"UserId",
			"UserName",
			"ContractIdentifier",
			"ContributionAmount",
			"ContributionRate",
			"SoulPower",
			"ProductionParams",
			"FarmInfo",
			"RecentlyActive",
			"Active",
			"CcMember",
			"Leech",
			"Finalized",
			"TimeCheatDetected",
			"Platform",
			"Autojoined",
			"BoostTokens",
			"BoostTokensSpent",
			"BuffHistory",
			"ChickenRunCooldown",
		},

		"FarmProductionParams": {
			"Elr",
			"Sr",
			"Ihr",
			"FarmPopulation",
			"FarmCapacity",
			"Delivered",
		},

		"PlayerFarmInfo": {
			"EquippedArtifacts",
			"EpicResearch",
			"CommonResearch",
		},
	}

	// Types that should be replaced with their snapshot versions
	snapshotReplacements = []string{
		"PlayerFarmInfo",
		"FarmProductionParams",
		"CompleteArtifact",
		"ArtifactSpec",
		"CoopBuffState",
		"Backup_ResearchItem",
		"Backup_ActiveBoost",
	}
)

// ---- Helpers ----

func shouldExclude(fieldName string) bool {
	return slices.Contains(globalExcludes, fieldName)
}

func isWhitelisted(structName, fieldName string) bool {
	allowed, exists := snapshotFieldWhitelist[structName]
	if !exists {
		// If no whitelist defined for struct, keep all fields except globals
		return true
	}
	return slices.Contains(allowed, fieldName)
}

// ---- Snapshot Generator ----

// GenerateSnapshotStruct dynamically creates a "flattened" snapshot struct
// from a protobuf-derived type. It removes pointer indirection for basic
// fields (float, int, string, bool) for performance and simplicity,
// but keeps slices and nested structs intact.
//
// This is designed for creating lightweight(e.g., for analytics or storage).
func GenerateSnapshotStruct(obj any) string {
	t := reflect.TypeOf(obj).Elem()
	var b strings.Builder

	snapshotName := fmt.Sprintf("%s_Snapshot", t.Name())
	fmt.Fprintf(&b, "type %s struct {\n", snapshotName)

	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)

		// Skip internal protobuf fields
		if shouldExclude(f.Name) {
			continue
		}
		// Only include whitelisted fields
		if !isWhitelisted(t.Name(), f.Name) {
			continue
		}

		// Start with the field type string
		fieldType := strings.TrimPrefix(f.Type.String(), "*")
		fieldType = strings.ReplaceAll(fieldType, "ei.", "")

		// Replace known protobuf types with snapshot versions
		for _, tname := range snapshotReplacements {
			if strings.Contains(fieldType, tname) {
				fieldType = strings.ReplaceAll(fieldType, tname, tname+"_Snapshot")
			}
		}

		// Determine field kind
		kind := f.Type.Kind()

		switch kind {
		case reflect.Pointer:
			// Flatten pointer to base type if it’s a basic value type
			elem := f.Type.Elem().Kind()
			switch elem {
			case reflect.Bool, reflect.String, reflect.Float32, reflect.Float64,
				reflect.Int, reflect.Int32, reflect.Int64,
				reflect.Uint, reflect.Uint32, reflect.Uint64:
				// Drop pointer for scalars
				fieldType = strings.TrimPrefix(fieldType, "*")
			default:
				// Keep pointer for complex or nested structs
				fieldType = "*" + fieldType
			}

		case reflect.Slice:
			// Keep slices as-is
			fieldType = "[]" + fieldType
		}

		// Add JSON tag
		jsonTag := fmt.Sprintf("`json:\"%s,omitempty\"`", strings.ToLower(f.Name))
		fmt.Fprintf(&b, "\t%s %s %s\n", f.Name, fieldType, jsonTag)
	}

	fmt.Fprintf(&b, "}\n\n")
	return b.String()
}

// ---- Snapshot Writer ----

// GenerateSnapshots generates lightweight snapshot structs for selected
// protobuf-derived types defined in the ei package. It writes the generated Go
// code to the specified output path under the given package name.
//
// Each snapshot struct includes only fields defined in the whitelist
// (snapshotFieldWhitelist) and replaces nested protobuf types with their
// corresponding snapshot versions as defined in snapshotReplacements.
//
// Run this manually with:
//
//	go run ./src/bottools/cmd/run_snapshots.go
func GenerateSnapshots(outputPath, packageName string) error {
	var b strings.Builder

	// File header
	fmt.Fprintf(&b, `// Code generated by snapshotgen.go; DO NOT EDIT.
// This file contains lightweight snapshot structs derived from protobuf types.
// Run "go run ./src/bottools/cmd/run_snapshots.go" to regenerate.

package %s

`, packageName)

	// Structs to snapshot
	structs := []any{
		&ei.ContractCoopStatusResponse_ContributionInfo{},
		&ei.FarmProductionParams{},
		&ei.PlayerFarmInfo{},
		&ei.CompleteArtifact{},
		&ei.ArtifactSpec{},
		&ei.CoopBuffState{},
	}

	// Generate each snapshot struct
	for _, s := range structs {
		b.WriteString(GenerateSnapshotStruct(s))
	}

	// Write the generated code to file
	if err := os.WriteFile(outputPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("failed to write snapshot file: %w", err)
	}

	fmt.Printf("✅ Snapshot file created: %s\n", outputPath)
	return nil
}
